Delete network
Brendan-McDonnell/autopi pull request #128
Opened 2021-06-11 19:56 UTC by iradley2

# Description of changes
Created script to delete desired network
# Outstanding changes
no update network feature (stretch)
# Outstanding questions

# Documentation updates
- [x] I updated usage documentation as appropriate
- [x] I updated installation documentation as appropriate
- [x] I updated implementation documentation as appropriate
- [x] I updated technical considerations documentation as appropriate

# Issues closed
closes #35

2021-06-13 04:31 UTC, B-McDonnell requested changes
Move a bunch of this function to `util/network_interface.py`.

Also, what happens if there are multiple networks with the same SSID?

2021-06-13 09:22 UTC, zjgamble approved these changes

2021-06-14 03:30 UTC, B-McDonnell requested changes
Also, add docs

2021-06-14 05:24 UTC, B-McDonnell requested changes
Still needs to pass code standards and have docs in addition to these changes

2021-06-14 05:40 UTC, zjgamble approved these changes

2021-06-14 06:48 UTC, closed without merging